### ISSUE TITLE
KeyError: "type"

### ISSUE THREAD

**Issue by tandej** [Steffen-W/KiCad-Parasitics#1]
This is a really cool project idea and I'm glad that I caught it in the plugin manager. I haven't been able to use it yet, though, because...

```
Traceback (most recent call last):
  File ".../kicad/7.0/3rdparty/plugins/com_github_Steffen-W_KiCad-Parasitics/__init__.py", line 51, in Run
    ItemList = Get_PCB_Elements(board, connect)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../kicad/7.0/3rdparty/plugins/com_github_Steffen-W_KiCad-Parasitics/Get_PCB_Elements.py", line 227, in Get_PCB_Elements
    if d["type"] == "ZONE":
       ~^^^^^^^^
KeyError: 'type'
```

## Environment:
Debian bookworm, using Kicad 7.0 (installed via apt with `sudo apt install kicad-libraries="7.0.7+dfsg-1~bpo12+1"` from bookworm-backports.

## Reproduction steps:
![image](https://github.com/Steffen-W/KiCad-Parasitics/assets/79597979/4e615951-4cd4-431d-907e-f4893ee404ab)
Two pads in the same net.

![image](https://github.com/Steffen-W/KiCad-Parasitics/assets/79597979/8d00f09a-3ef6-4b51-a0d3-e071e3c7fb93)
With nothing, selected, works as expected.

![image](https://github.com/Steffen-W/KiCad-Parasitics/assets/79597979/541e571b-8f7a-4812-898b-7f3c3b7d3073)
When two pads are selected, this happens. Not sure if this is the intended error message, but at least it's handled?

![image](https://github.com/Steffen-W/KiCad-Parasitics/assets/79597979/904e8857-a1b1-4f49-93dd-a2980d3bfd23)
![image](https://github.com/Steffen-W/KiCad-Parasitics/assets/79597979/63eb7f8a-0b89-4ce2-bbac-c2bf06ce14e8)
And activating the plugin, even with nothing selected, causes the error.

![image](https://github.com/Steffen-W/KiCad-Parasitics/assets/79597979/8736f6a5-4d99-4cae-a6fe-1dd8821f7c82)
Same thing if the pads are selected, and again if all the traces in the middle are as well.

Thanks for looking into this, the idea looks promising.

**Comment by Steffen-W** [comment]
Hi @TandeJ,
I'm glad you're trying out the plugin. The new version, should be there from today or tomorrow is less buggy. Nevertheless, this problem is what you describe there guaranteed also. If possible I would be very happy if you can send me the PCB file.

I assume that you have an element of conduction that I have not considered so far. I would like to see which one it is. If my guess is correct you can try this:
https://github.com/Steffen-W/KiCad-Parasitics/blob/98622d42940a7d8c4feb98fcf2e5beacca850e43/plugins/Get_PCB_Elements.py#L171-L180

``` python
        elif type(track) is pcbnew.PCB_TRACK:
            temp["type"] = "WIRE"
            temp["Start"] = ToMM(track.GetStart())
            temp["End"] = ToMM(track.GetEnd())
            temp["Width"] = ToMM(track.GetWidth())
            temp["Length"] = ToMM(track.GetLength())
            if track.GetLength() == 0:
                continue
            temp["Layer"] = [track.GetLayer()]
            temp["connStart"], temp["connEnd"] = getConnections(track, connect)
        else:
            continue
```

add this else condition at the end. I can only imagine that this is where the error comes from. 

You can access the file via the Plugin manager, Open Package Directory,  plugins/com_github_Steffen-W_KiCad-Parasitics/Get_Parasitic.py.
Thank you very much. I will take care of fixing the error. The plugin is still young and certainly buggy.
